GET http://localhost:5000/users/
Content-Type: application/json

{
  "email": "doe@mail.com",
  "password": "112233"
}

###

GET http://localhost:5000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYmNjY2YzYWM2ODYzMDRlNTBhYmE4ZCIsImlhdCI6MTYwNjI0NjE5MH0.n4VibcKjdN2Uaqd722oFwM9aHAfbPOg1gE2Yu11MzSs

###


POST http://localhost:5000/users/
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@mail.com",
  "password": "11223344",
}